<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <?php
    //What Is an Error?

    //An error is a problem that stops or affects program execution.

    // Example:

    // echo $variable;


    // If $variable is not defined → PHP generates a notice.

    // Errors are usually generated by:

    // Syntax mistakes

    // Undefined variables

    // Wrong function usage

    // Missing files

    // | Type        | Meaning                 |
    // | ----------- | ----------------------- |
    // | Parse Error | Syntax mistake          |
    // | Fatal Error | Stops script completely |
    // | Warning     | Non-fatal problem       |
    // | Notice      | Minor issue             |

    /*
   // What Is an Exception? //

    An exception is an object representing an error condition.

    Instead of crashing the script, we can:
    Catch it
    Handle it
    Continue execution
    Exceptions are more controlled and modern than traditional errors.

🔷 Difference Between Error and Exception

| Error             | Exception         |
| ----------------- | ----------------- |
| Usually automatic | Must be thrown    |
| Can stop script   | Can be caught     |
| Less flexible     | More controllable |
| Traditional       | Object-Oriented   |

DIE FUNCTION
🔹 What is die()?
die() immediately terminates script execution.
It is equivalent to:
exit();


*/

    $file = "data.txt";

    if (!file_exists($file)) {
        die("File not found.");
    }

    echo "File exists.";


    // If file doesn’t exist → script stops immediately.

    // 🔹 When To Use die()

    // Simple validation
    // Quick failure
    // Small scripts
    // Not recommended for large systems

    //=========================CUSTOM ERROR FUNCTIONS============================//
    // Why Create Custom Error Handler?By default, PHP prints error messages like:
    // Warning: Undefined variable...
    // But in production systems, we want:

    // Clean messages
    // Logging
    // Better formatting

    //============creating custom error funcions==================

    //Step 1: Create Custom Function
    function myErrorHandler($errno, $errstr, $errfile, $errline)
    {
        echo "Error: [$errno] $errstr in $errfile on line $errline";
    }
    //step 2:register it 
    //Now php will use your function instead of default error display 
    set_error_handler("myErrorHandler");

    echo $undefinedVariable;
    //Instead of default PHP error → your custom message appears


    //======================= TRY AND CATCH =================

    // try {
    //      risky code
    // } catch (Exception $e) {
    //     handle exception
    // }


    try {
        throw new Exception("something went wrong.");
    } catch (Exception $e) {
        echo "Caught exception:" . $e->getMessage();
    }

    //What is throw? throw is used to manually generate an exception.
    //throw new Exception("Invalid input");

    $age = -5;

    try {
        if ($age < 0) {
            throw new Exception("Age cannot be negative.");
        }
        echo "Valid age.";
    } catch (Exception $e) {
        echo "Error: " . $e->getMessage();
    }
    //If condition is wrong → exception thrown → caught → handled.




    function checkNumber($number)
    {

        if ($number > 10) {
            throw new Exception("Number is too large.");
        }

        return $number;
    }

    try {

        echo checkNumber(15);
    } catch (Exception $e) {

        echo "Exception caught: " . $e->getMessage();
    }

    // Real System-Level Flow

    // When exception is thrown:
    // PHP creates Exception object
    // Execution stops inside try
    // PHP searches for matching catch
    // If found → executes catch
    // If not → fatal error


    try {
        // code
    } catch (TypeError $e) {
        // type error
    } catch (Exception $e) {
        // general exception
    }


    // | Concept              | Purpose                 | Stops Script?      |
    // | -------------------- | ----------------------- | ------------------ |
    // | die()                | Immediate termination   | Yes                |
    // | Custom error handler | Control error output    | No                 |
    // | throw                | Create exception        | Yes (until caught) |
    // | try-catch            | Handle exception safely | No                 |



    // Key Understanding
    // die() = emergency stop
    // throw = signal problem
    // try-catch = controlled handling
    // Custom error handler = control formatting of errors






    // ----------------------------------------
    // 1️⃣ CUSTOM ERROR HANDLER
    // ----------------------------------------

    function customErrorHandler($errno, $errstr, $errfile, $errline)
    {
        $message = "Error [$errno]: $errstr in $errfile on line $errline\n";
        // Log error to file
        file_put_contents("error_log.txt", $message, FILE_APPEND);
        echo "A system error occurred. Please try again later.";
    }

    set_error_handler("customErrorHandler");

    //========================== $errno  ============================//
    //So $errno tells you the error classification.

    // | Constant         | Meaning                |
    // | ---------------- | ---------------------- |
    // | `E_ERROR`        | Fatal error            |
    // | `E_WARNING`      | Warning                |
    // | `E_NOTICE`       | Notice                 |
    // | `E_PARSE`        | Syntax error           |
    // | `E_USER_ERROR`   | User-triggered error   |
    // | `E_USER_WARNING` | User-triggered warning |
    // | `E_USER_NOTICE`  | User-triggered notice  |

    //================ $errstr — Error String (Error Message) =================//

    // a string describing the error in human-readable form.
    //$errfile — File Where Error Occurred What it is:The full path of the PHP file where the error happened.
    //$errline — Line Number of Error What it is: The exact line number inside the file where the error occurred.


    // function customErrorHandler($errno, $errstr, $errfile, $errline)
    // {
    //     echo "Error Type: $errno <br>";
    //     echo "Message: $errstr <br>";
    //     echo "File: $errfile <br>";
    //     echo "Line: $errline <br>";
    // }

    // set_error_handler("customErrorHandler");

    // echo $undefinedVariable;




    // | Variable   | Meaning            |
    // | ---------- | ------------------ |
    // | `$errno`   | What type of error |
    // | `$errstr`  | What happened      |
    // | `$errfile` | Where it happened  |
    // | `$errline` | Exact line number  |




    // ----------------------------------------
    // 2️⃣ CHECK IF UPLOAD DIRECTORY EXISTS
    // ----------------------------------------

    $uploadDir = "uploads/";

    if (!is_dir($uploadDir)) {
        die("Upload directory does not exist. Contact administrator.");
    }


    // ----------------------------------------
    // 3️⃣ FILE PROCESSING
    // ----------------------------------------

    if (isset($_FILES['myfile'])) {

        try {

            $fileName = basename($_FILES['myfile']['name']);
            $tempName = $_FILES['myfile']['tmp_name'];
            $fileSize = $_FILES['myfile']['size'];
            $fileError = $_FILES['myfile']['error'];
            $fileType = strtolower(pathinfo($fileName, PATHINFO_EXTENSION));

            // ----------------------------------------
            // 4️⃣ CHECK FOR UPLOAD ERRORS
            // ----------------------------------------

            if ($fileError !== 0) {
                throw new Exception("File upload error occurred.");
            }

            // ----------------------------------------
            // 5️⃣ VALIDATE FILE SIZE
            // ----------------------------------------

            if ($fileSize > 2000000) { // 2MB limit
                throw new Exception("File is too large.");
            }

            // ----------------------------------------
            // 6️⃣ VALIDATE FILE TYPE
            // ----------------------------------------

            $allowedTypes = ["jpg", "png", "pdf"];

            if (!in_array($fileType, $allowedTypes)) {
                throw new Exception("Invalid file type.");
            }

            // ----------------------------------------
            // 7️⃣ MOVE FILE
            // ----------------------------------------

            $newFileName = uniqid("file_", true) . "." . $fileType;
            $destination = $uploadDir . $newFileName;

            if (!move_uploaded_file($tempName, $destination)) {
                throw new Exception("Failed to move uploaded file.");
            }

            echo "File uploaded successfully.";
        } catch (Exception $e) {

            // ----------------------------------------
            // 8️⃣ HANDLE EXCEPTION
            // ----------------------------------------

            $errorMessage = "Exception: " . $e->getMessage() . "\n";

            file_put_contents("error_log.txt", $errorMessage, FILE_APPEND);

            echo "Upload failed: " . $e->getMessage();
        }
    }


    // | Feature              | Where It Is Used          | Why                   |
    // | -------------------- | ------------------------- | --------------------- |
    // | `die()`              | If uploads folder missing | Immediate termination |
    // | Custom error handler | `set_error_handler()`     | Control PHP warnings  |
    // | `throw`              | When validation fails     | Generate exception    |
    // | `try`                | Wrap risky code           | Monitor for failure   |
    // | `catch`              | Handles thrown exceptions | Prevent crash         |
    // | Logging              | `file_put_contents()`     | Store error records   |


    // | Tool                  | Purpose                     |
    // | --------------------- | --------------------------- |
    // | `die()`               | Emergency stop              |
    // | `set_error_handler()` | Override default PHP errors |
    // | `throw`               | Signal problem              |
    // | `try-catch`           | Controlled handling         |
    // | Logging               | Debugging & monitoring      |










    ?>
</body>

</html>